name: Tests
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Manual Tests'
        required: true
        default: 'latest'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm i
      - name: Run tests
        env:
          MAIN_STR: ${{ env.MAIN_STR }}
        run: npm start
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
